# Before compose up run this "docker network create caddy"
# aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 155635619005.dkr.ecr.us-east-2.amazonaws.com
version: "3"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine

    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    depends_on:
      - smarthealthui
  smarthealthui:
    image: 155635619005.dkr.ecr.us-east-2.amazonaws.com/githubactionapptest:react_demo_image

    restart: always
    networks:
      - caddy
    labels:
      caddy.tls: "internal"
      caddy: testncare.com
      caddy.reverse_proxy: "{{upstreams 3009}}"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30
networks:
  caddy:
    external: true

volumes:
  caddy_data: {}
